FROM node:argon

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY .env /usr/src/app/
COPY .eslintignore /usr/src/app/
COPY .eslintrc /usr/src/app/
RUN npm install --quiet
RUN npm install -g nodemon

EXPOSE 3000

CMD [ "nodemon", "-L" ]
